from pathlib import Path
import os
import streamlit as st
from sqlalchemy import create_engine, text

BASE_DIR = Path(__file__).resolve().parent
DATA_DIR = BASE_DIR / "data"
DATA_DIR.mkdir(parents=True, exist_ok=True)
LOCAL_DB_PATH = DATA_DIR / "auction_v5_local.db"


def build_database_url_v5():
    env_url = os.getenv("DATABASE_URL", "").strip()
    if env_url:
        return env_url

    db = st.secrets.get("database", {}) if hasattr(st, "secrets") else {}
    if db:
        dialect = str(db.get("dialect", "postgresql")).strip()
        host = str(db.get("host", "")).strip()
        port = str(db.get("port", "5432")).strip()
        database = str(db.get("database", "")).strip()
        username = str(db.get("username", "")).strip()
        password = str(db.get("password", "")).strip()
        sslmode = str(db.get("sslmode", "require")).strip()
        return f"{dialect}+psycopg2://{username}:{password}@{host}:{port}/{database}?sslmode={sslmode}"

    return f"sqlite:///{LOCAL_DB_PATH.as_posix()}"


DATABASE_URL = build_database_url_v5()
IS_POSTGRES = DATABASE_URL.startswith("postgresql")

ENGINE_KWARGS = {"future": True, "pool_pre_ping": True}
if IS_POSTGRES:
    ENGINE_KWARGS.update({
        "pool_timeout": 10,
        "pool_recycle": 1800,
        "connect_args": {
            "connect_timeout": 5,
            "options": "-c statement_timeout=15000 -c lock_timeout=5000",
        },
    })

engine = create_engine(DATABASE_URL, **ENGINE_KWARGS)


def is_postgres_v5():
    return IS_POSTGRES


def healthcheck_db_v5():
    with engine.begin() as conn:
        conn.execute(text("SELECT 1"))


def init_db_v5():
    with engine.begin() as conn:
        if is_postgres_v5():
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS teams (
                    team_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    team_name TEXT UNIQUE NOT NULL,
                    cap_limit DOUBLE PRECISION NOT NULL
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS users (
                    user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    email TEXT UNIQUE NOT NULL,
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL,
                    team_id INTEGER NULL,
                    is_active INTEGER NOT NULL DEFAULT 1,
                    must_change_password INTEGER NOT NULL DEFAULT 1,
                    FOREIGN KEY(team_id) REFERENCES teams(team_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS players (
                    player_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    player_name TEXT NOT NULL,
                    position TEXT NOT NULL,
                    owner_team_id INTEGER NULL,
                    status TEXT NOT NULL DEFAULT 'OPEN',
                    closed_at TEXT NULL,
                    UNIQUE(player_name, position),
                    FOREIGN KEY(owner_team_id) REFERENCES teams(team_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS bids (
                    bid_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    player_id INTEGER NOT NULL,
                    team_id INTEGER NOT NULL,
                    amount DOUBLE PRECISION NOT NULL,
                    years INTEGER NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NULL,
                    deleted_at TEXT NULL,
                    delete_reason TEXT NULL,
                    is_valid INTEGER NOT NULL DEFAULT 1,
                    is_active INTEGER NOT NULL DEFAULT 1,
                    is_renewal INTEGER NOT NULL DEFAULT 0,
                    invalid_reason TEXT NULL,
                    created_by_user_id INTEGER NULL,
                    updated_by_user_id INTEGER NULL,
                    deleted_by_user_id INTEGER NULL,
                    FOREIGN KEY(player_id) REFERENCES players(player_id),
                    FOREIGN KEY(team_id) REFERENCES teams(team_id),
                    FOREIGN KEY(created_by_user_id) REFERENCES users(user_id),
                    FOREIGN KEY(updated_by_user_id) REFERENCES users(user_id),
                    FOREIGN KEY(deleted_by_user_id) REFERENCES users(user_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS player_state (
                    player_id INTEGER PRIMARY KEY,
                    active_bid_id INTEGER NULL,
                    active_team_id INTEGER NULL,
                    active_amount DOUBLE PRECISION NULL,
                    active_years INTEGER NULL,
                    active_at TEXT NULL,
                    expires_at TEXT NULL,
                    status TEXT NOT NULL DEFAULT 'OPEN',
                    is_renewal INTEGER NOT NULL DEFAULT 0,
                    FOREIGN KEY(player_id) REFERENCES players(player_id),
                    FOREIGN KEY(active_bid_id) REFERENCES bids(bid_id),
                    FOREIGN KEY(active_team_id) REFERENCES teams(team_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS audit_log (
                    audit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    event_time TEXT NOT NULL,
                    username TEXT NULL,
                    action TEXT NOT NULL,
                    entity_type TEXT NOT NULL,
                    entity_id TEXT NULL,
                    details TEXT NULL
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS home_tabs (
                    tab_key TEXT PRIMARY KEY,
                    tab_label TEXT NOT NULL,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    sort_order INTEGER NOT NULL DEFAULT 0,
                    allow_posts BOOLEAN NOT NULL DEFAULT TRUE,
                    allow_comments BOOLEAN NOT NULL DEFAULT TRUE
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS rules_documents (
                    rule_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title TEXT NOT NULL,
                    content_md TEXT NOT NULL,
                    version TEXT,
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_by TEXT,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS calendar_events (
                    event_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    title TEXT NOT NULL,
                    category TEXT NOT NULL,
                    start_date DATE NOT NULL,
                    end_date DATE,
                    season TEXT,
                    status TEXT,
                    notes TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS draft_board (
                    draft_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    season TEXT NOT NULL,
                    round INTEGER NOT NULL,
                    pick_number INTEGER NOT NULL,
                    original_team_id INTEGER,
                    current_team_id INTEGER,
                    selected_player TEXT,
                    selected_player_id INTEGER,
                    status TEXT NOT NULL DEFAULT 'OPEN',
                    notes TEXT,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    UNIQUE (season, round, pick_number)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS link_items (
                    link_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    section TEXT NOT NULL,
                    label TEXT NOT NULL,
                    url TEXT NOT NULL,
                    description TEXT,
                    is_active BOOLEAN NOT NULL DEFAULT TRUE,
                    sort_order INTEGER NOT NULL DEFAULT 0,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS home_posts (
                    post_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tab_key TEXT NOT NULL REFERENCES home_tabs(tab_key),
                    author TEXT NOT NULL,
                    title TEXT NOT NULL,
                    content_md TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'PUBLISHED',
                    is_pinned BOOLEAN NOT NULL DEFAULT FALSE,
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS wall_comments (
                    comment_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                    tab_key TEXT NOT NULL REFERENCES home_tabs(tab_key),
                    post_id BIGINT NULL REFERENCES home_posts(post_id) ON DELETE CASCADE,
                    author TEXT NOT NULL,
                    comment_text TEXT NOT NULL,
                    related_pick_id BIGINT NULL REFERENCES draft_board(draft_id),
                    status TEXT NOT NULL DEFAULT 'VISIBLE',
                    created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
                    is_pinned BOOLEAN NOT NULL DEFAULT FALSE
                )
            """))

            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_home_posts_tab ON home_posts (tab_key, status, is_pinned, created_at DESC)"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_wall_comments_tab ON wall_comments (tab_key, created_at DESC)"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_wall_comments_post ON wall_comments (post_id, created_at ASC)"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_link_items_section ON link_items (section, is_active, sort_order)"))
            conn.execute(text("CREATE INDEX IF NOT EXISTS idx_calendar_events_dates ON calendar_events (start_date, end_date)"))

        else:
            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS teams (
                    team_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    team_name TEXT UNIQUE NOT NULL,
                    cap_limit REAL NOT NULL
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS users (
                    user_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    email TEXT UNIQUE NOT NULL,
                    password_hash TEXT NOT NULL,
                    role TEXT NOT NULL,
                    team_id INTEGER NULL,
                    is_active INTEGER NOT NULL DEFAULT 1,
                    must_change_password INTEGER NOT NULL DEFAULT 1,
                    FOREIGN KEY(team_id) REFERENCES teams(team_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS players (
                    player_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    player_name TEXT NOT NULL,
                    position TEXT NOT NULL,
                    owner_team_id INTEGER NULL,
                    status TEXT NOT NULL DEFAULT 'OPEN',
                    closed_at TEXT NULL,
                    UNIQUE(player_name, position),
                    FOREIGN KEY(owner_team_id) REFERENCES teams(team_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS bids (
                    bid_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    player_id INTEGER NOT NULL,
                    team_id INTEGER NOT NULL,
                    amount REAL NOT NULL,
                    years INTEGER NOT NULL,
                    created_at TEXT NOT NULL,
                    updated_at TEXT NULL,
                    deleted_at TEXT NULL,
                    delete_reason TEXT NULL,
                    is_valid INTEGER NOT NULL DEFAULT 1,
                    is_active INTEGER NOT NULL DEFAULT 1,
                    is_renewal INTEGER NOT NULL DEFAULT 0,
                    invalid_reason TEXT NULL,
                    created_by_user_id INTEGER NULL,
                    updated_by_user_id INTEGER NULL,
                    deleted_by_user_id INTEGER NULL,
                    FOREIGN KEY(player_id) REFERENCES players(player_id),
                    FOREIGN KEY(team_id) REFERENCES teams(team_id),
                    FOREIGN KEY(created_by_user_id) REFERENCES users(user_id),
                    FOREIGN KEY(updated_by_user_id) REFERENCES users(user_id),
                    FOREIGN KEY(deleted_by_user_id) REFERENCES users(user_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS player_state (
                    player_id INTEGER PRIMARY KEY,
                    active_bid_id INTEGER NULL,
                    active_team_id INTEGER NULL,
                    active_amount REAL NULL,
                    active_years INTEGER NULL,
                    active_at TEXT NULL,
                    expires_at TEXT NULL,
                    status TEXT NOT NULL DEFAULT 'OPEN',
                    is_renewal INTEGER NOT NULL DEFAULT 0,
                    FOREIGN KEY(player_id) REFERENCES players(player_id),
                    FOREIGN KEY(active_bid_id) REFERENCES bids(bid_id),
                    FOREIGN KEY(active_team_id) REFERENCES teams(team_id)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS audit_log (
                    audit_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    event_time TEXT NOT NULL,
                    username TEXT NULL,
                    action TEXT NOT NULL,
                    entity_type TEXT NOT NULL,
                    entity_id TEXT NULL,
                    details TEXT NULL
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS home_tabs (
                    tab_key TEXT PRIMARY KEY,
                    tab_label TEXT NOT NULL,
                    is_active INTEGER NOT NULL DEFAULT 1,
                    sort_order INTEGER NOT NULL DEFAULT 0,
                    allow_posts INTEGER NOT NULL DEFAULT 1,
                    allow_comments INTEGER NOT NULL DEFAULT 1
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS rules_documents (
                    rule_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title TEXT NOT NULL,
                    content_md TEXT NOT NULL,
                    version TEXT,
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_by TEXT,
                    is_active INTEGER NOT NULL DEFAULT 1
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS calendar_events (
                    event_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    title TEXT NOT NULL,
                    category TEXT NOT NULL,
                    start_date TEXT NOT NULL,
                    end_date TEXT,
                    season TEXT,
                    status TEXT,
                    notes TEXT,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS draft_board (
                    draft_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    season TEXT NOT NULL,
                    round INTEGER NOT NULL,
                    pick_number INTEGER NOT NULL,
                    original_team_id INTEGER,
                    current_team_id INTEGER,
                    selected_player TEXT,
                    selected_player_id INTEGER,
                    status TEXT NOT NULL DEFAULT 'OPEN',
                    notes TEXT,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    UNIQUE (season, round, pick_number)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS link_items (
                    link_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    section TEXT NOT NULL,
                    label TEXT NOT NULL,
                    url TEXT NOT NULL,
                    description TEXT,
                    is_active INTEGER NOT NULL DEFAULT 1,
                    sort_order INTEGER NOT NULL DEFAULT 0,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS home_posts (
                    post_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    tab_key TEXT NOT NULL,
                    author TEXT NOT NULL,
                    title TEXT NOT NULL,
                    content_md TEXT NOT NULL,
                    status TEXT NOT NULL DEFAULT 'PUBLISHED',
                    is_pinned INTEGER NOT NULL DEFAULT 0,
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    updated_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    FOREIGN KEY(tab_key) REFERENCES home_tabs(tab_key)
                )
            """))

            conn.execute(text("""
                CREATE TABLE IF NOT EXISTS wall_comments (
                    comment_id INTEGER PRIMARY KEY AUTOINCREMENT,
                    tab_key TEXT NOT NULL,
                    post_id INTEGER NULL,
                    author TEXT NOT NULL,
                    comment_text TEXT NOT NULL,
                    related_pick_id INTEGER NULL,
                    status TEXT NOT NULL DEFAULT 'VISIBLE',
                    created_at TEXT NOT NULL DEFAULT CURRENT_TIMESTAMP,
                    is_pinned INTEGER NOT NULL DEFAULT 0,
                    FOREIGN KEY(tab_key) REFERENCES home_tabs(tab_key),
                    FOREIGN KEY(post_id) REFERENCES home_posts(post_id),
                    FOREIGN KEY(related_pick_id) REFERENCES draft_board(draft_id)
                )
            """))